import pandas as pd
import argparse

from main.data.cvat_parser import CvatXmlParser


def xml_to_csv(path):
    """Iterates through all .xml files (generated by labelImg) in a given directory and combines them in a single Pandas datagrame.

    Parameters:
    ----------
    path : {str}
        The path containing the .xml files
    Returns
    -------
    Pandas DataFrame
        The produced dataframe
    """

    xml = CvatXmlParser(path_to_xml=path)
    full_xml = xml.parsed

    xml_list = []
    for name, data in full_xml.images.items():
        value = (
            data.properties.raw_name,
            data.properties.w,
            data.properties.h,
            data.objects.labels,
            data.objects.xmins,
            data.objects.ymins,
            data.objects.xmaxs,
            data.objects.ymaxs
        )
        xml_list.append(value)
    column_name = ['filename', 'width', 'height',
                'class', 'xmin', 'ymin', 'xmax', 'ymax']
    xml_df = pd.DataFrame(xml_list, columns=column_name)
    return xml_df


if __name__ == '__main__':

    import os
    data_dir = r"/Users/jbheurtel/Desktop/MT2/dataset/"

    parser = argparse.ArgumentParser(
        description="Sample TensorFlow XML-to-CSV converter")
    parser.add_argument("-i", "--inputDir", type=str)
    args = parser.parse_args()

    input_dir = os.path.join(data_dir, "cvat", args.inputDir, "annotations.xml")
    output_file = os.path.join(data_dir, "tfrecords" , args.inputDir + ".csv")

    xml_df = xml_to_csv(input_dir)
    xml_df.to_csv(output_file, index=None)
